version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip-compile"
    directory: "/"
    schedule:
      interval: "monthly"