
name: Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version:
        - '3.12'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('package.json') }}-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate
        env:
            DJANGO_SETTINGS_MODULE: website.settings
            DATABASE_HOST: localhost
            DATABASE_PORT: 5432
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: blog
      - name: Run Tests
        run: |
          coverage run -m pytest
        env:
            DJANGO_SETTINGS_MODULE: website.settings
            DATABASE_HOST: localhost
            DATABASE_PORT: 5432
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: blog

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}